/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SessionPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelPool"
      | "cancelled"
      | "contribute"
      | "contributions"
      | "contributors"
      | "deadline"
      | "fundsReleased"
      | "getContribution"
      | "getContributors"
      | "getPoolStats"
      | "getProgress"
      | "goalAmount"
      | "goalReached"
      | "lecturer"
      | "releaseFunds"
      | "requestRefund"
      | "sessionId"
      | "totalContributed"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContributionReceived"
      | "FundsReleased"
      | "GoalReached"
      | "PoolCancelled"
      | "RefundIssued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cancelled", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contributors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deadline", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundsReleased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContribution",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProgress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "goalAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "goalReached",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lecturer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRefund",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sessionId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalContributed",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "cancelPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelled", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deadline", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundsReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "goalAmount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "goalReached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lecturer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sessionId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalContributed",
    data: BytesLike
  ): Result;
}

export namespace ContributionReceivedEvent {
  export type InputTuple = [contributor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [contributor: string, amount: bigint];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [lecturer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [lecturer: string, amount: bigint];
  export interface OutputObject {
    lecturer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GoalReachedEvent {
  export type InputTuple = [totalAmount: BigNumberish];
  export type OutputTuple = [totalAmount: bigint];
  export interface OutputObject {
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundIssuedEvent {
  export type InputTuple = [contributor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [contributor: string, amount: bigint];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SessionPool extends BaseContract {
  connect(runner?: ContractRunner | null): SessionPool;
  waitForDeployment(): Promise<this>;

  interface: SessionPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelPool: TypedContractMethod<[], [void], "nonpayable">;

  cancelled: TypedContractMethod<[], [boolean], "view">;

  contribute: TypedContractMethod<[], [void], "payable">;

  contributions: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  contributors: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  deadline: TypedContractMethod<[], [bigint], "view">;

  fundsReleased: TypedContractMethod<[], [boolean], "view">;

  getContribution: TypedContractMethod<
    [contributor: AddressLike],
    [bigint],
    "view"
  >;

  getContributors: TypedContractMethod<[], [string[]], "view">;

  getPoolStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean, boolean, boolean, bigint] & {
        _totalContributed: bigint;
        _goalAmount: bigint;
        _contributorCount: bigint;
        _goalReached: boolean;
        _fundsReleased: boolean;
        _cancelled: boolean;
        _timeRemaining: bigint;
      }
    ],
    "view"
  >;

  getProgress: TypedContractMethod<[], [bigint], "view">;

  goalAmount: TypedContractMethod<[], [bigint], "view">;

  goalReached: TypedContractMethod<[], [boolean], "view">;

  lecturer: TypedContractMethod<[], [string], "view">;

  releaseFunds: TypedContractMethod<[], [void], "nonpayable">;

  requestRefund: TypedContractMethod<[], [void], "nonpayable">;

  sessionId: TypedContractMethod<[], [string], "view">;

  totalContributed: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelPool"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "contributors"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fundsReleased"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getContribution"
  ): TypedContractMethod<[contributor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContributors"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPoolStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean, boolean, boolean, bigint] & {
        _totalContributed: bigint;
        _goalAmount: bigint;
        _contributorCount: bigint;
        _goalReached: boolean;
        _fundsReleased: boolean;
        _cancelled: boolean;
        _timeRemaining: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProgress"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "goalAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "goalReached"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lecturer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRefund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sessionId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalContributed"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ContributionReceived"
  ): TypedContractEvent<
    ContributionReceivedEvent.InputTuple,
    ContributionReceivedEvent.OutputTuple,
    ContributionReceivedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "GoalReached"
  ): TypedContractEvent<
    GoalReachedEvent.InputTuple,
    GoalReachedEvent.OutputTuple,
    GoalReachedEvent.OutputObject
  >;
  getEvent(
    key: "PoolCancelled"
  ): TypedContractEvent<
    PoolCancelledEvent.InputTuple,
    PoolCancelledEvent.OutputTuple,
    PoolCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RefundIssued"
  ): TypedContractEvent<
    RefundIssuedEvent.InputTuple,
    RefundIssuedEvent.OutputTuple,
    RefundIssuedEvent.OutputObject
  >;

  filters: {
    "ContributionReceived(address,uint256)": TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;
    ContributionReceived: TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;

    "FundsReleased(address,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "GoalReached(uint256)": TypedContractEvent<
      GoalReachedEvent.InputTuple,
      GoalReachedEvent.OutputTuple,
      GoalReachedEvent.OutputObject
    >;
    GoalReached: TypedContractEvent<
      GoalReachedEvent.InputTuple,
      GoalReachedEvent.OutputTuple,
      GoalReachedEvent.OutputObject
    >;

    "PoolCancelled()": TypedContractEvent<
      PoolCancelledEvent.InputTuple,
      PoolCancelledEvent.OutputTuple,
      PoolCancelledEvent.OutputObject
    >;
    PoolCancelled: TypedContractEvent<
      PoolCancelledEvent.InputTuple,
      PoolCancelledEvent.OutputTuple,
      PoolCancelledEvent.OutputObject
    >;

    "RefundIssued(address,uint256)": TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
    RefundIssued: TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
  };
}
